**Million Song Dataset + Spotify + Last.fm**

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving Music_Info[1].csv to Music_Info[1].csv

In [ ]:
import pandas as pd

music = pd.read_csv('Music_Info[1].csv')
music.head()

,track_id,name,artist,spotify_preview_url,spotify_id,tags,genre,year,duration_ms,danceability,...,key,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature
0,TRIOREW128F424EAF0,Mr. Brightside,The Killers,https://p.scdn.co/mp3-preview/4d26180e6961fd46...,09ZQ5TmUG8TSL56n0knqrj,"rock, alternative, indie, alternative_rock, in...",NaN,2004,222200,0.355,...,1,-4.360,1,0.0746,0.001190,0.000000,0.0971,0.240,148.114,4
1,TRRIVDJ128F429B0E8,Wonderwall,Oasis,https://p.scdn.co/mp3-preview/d012e536916c927b...,06UfBBDISthj1ZJAtX4xjj,"rock, alternative, indie, pop, alternative_roc...",NaN,2006,258613,0.409,...,2,-4.373,1,0.0336,0.000807,0.000000,0.2070,0.651,174.426,4
2,TROUVHL128F426C441,Come as You Are,Nirvana,https://p.scdn.co/mp3-preview/a1c11bb1cb231031...,0keNu0t0tqsWtExGM3nT1D,"rock, alternative, alternative_rock, 90s, grunge",RnB,1991,218920,0.508,...,4,-5.783,0,0.0400,0.000175,0.000459,0.0878,0.543,120.012,4
3,TRUEIND128F93038C4,Take Me Out,Franz Ferdinand,https://p.scdn.co/mp3-preview/399c401370438be4...,0ancVQ9wEcHVd0RrGICTE4,"rock, alternative, indie, alternative_rock, in...",NaN,2004,237026,0.279,...,9,-8.851,1,0.0371,0.000389,0.000655,0.1330,0.490,104.560,4
4,TRLNZBD128F935E4D8,Creep,Radiohead,https://p.scdn.co/mp3-preview/e7eb60e9466bc3a2...,01QoK9DA7VTeTSE3MNzp4I,"rock, alternative, indie, alternative_rock, in...",RnB,2008,238640,0.515,...,7,-9.935,1,0.0369,0.010200,0.000141,0.1290,0.104,91.841,4

In [ ]:
print(music.columns.tolist())

['track_id', 'name', 'artist', 'spotify_preview_url', 'spotify_id', 'tags', 'genre', 'year', 'duration_ms', 'danceability', 'energy', 'key', 'loudness', 'mode', 'speechiness', 'acousticness', 'instrumentalness', 'liveness', 'valence', 'tempo', 'time_signature']

In [ ]:
music = music[['name','artist','tags','genre','valence','energy','danceability','acousticness','tempo','spotify_preview_url', 'spotify_id']]
music.head()

,name,artist,tags,genre,valence,energy,danceability,acousticness,tempo,spotify_preview_url,spotify_id
0,Mr. Brightside,The Killers,"rock, alternative, indie, alternative_rock, in...",NaN,0.240,0.918,0.355,0.001190,148.114,https://p.scdn.co/mp3-preview/4d26180e6961fd46...,09ZQ5TmUG8TSL56n0knqrj
1,Wonderwall,Oasis,"rock, alternative, indie, pop, alternative_roc...",NaN,0.651,0.892,0.409,0.000807,174.426,https://p.scdn.co/mp3-preview/d012e536916c927b...,06UfBBDISthj1ZJAtX4xjj
2,Come as You Are,Nirvana,"rock, alternative, alternative_rock, 90s, grunge",RnB,0.543,0.826,0.508,0.000175,120.012,https://p.scdn.co/mp3-preview/a1c11bb1cb231031...,0keNu0t0tqsWtExGM3nT1D
3,Take Me Out,Franz Ferdinand,"rock, alternative, indie, alternative_rock, in...",NaN,0.490,0.664,0.279,0.000389,104.560,https://p.scdn.co/mp3-preview/399c401370438be4...,0ancVQ9wEcHVd0RrGICTE4
4,Creep,Radiohead,"rock, alternative, indie, alternative_rock, in...",RnB,0.104,0.430,0.515,0.010200,91.841,https://p.scdn.co/mp3-preview/e7eb60e9466bc3a2...,01QoK9DA7VTeTSE3MNzp4I

In [ ]:
music['tags'] = music['tags'].fillna('').str.lower()
music['tags_list'] = music['tags'].apply(lambda x: [t.strip() for t in x.split(',')])

In [ ]:
music['tags_list'].head()

0    [rock, alternative, indie, alternative_rock, i...
1    [rock, alternative, indie, pop, alternative_ro...
2    [rock, alternative, alternative_rock, 90s, gru...
3    [rock, alternative, indie, alternative_rock, i...
4    [rock, alternative, indie, alternative_rock, i...
Name: tags_list, dtype: object

In [ ]:
mood_tags = [
    'happy','sad','angry','calm','relax','relaxing','chill','chillout',
    'romantic','love','emotional','melancholy','melancholic','energetic',
    'upbeat','dance','danceable','soft','soothing','dark','bright','mellow',
    'aggressive','heavy','party','uplifting','beautiful','acoustic',

    # add these:
    'rage','furious','intense','chaotic','eerie','haunting','disturbing',
    'heartbreak','lonely','cry','depressed','pain','grief'
]

In [ ]:
def filter_mood_tags(taglist):
    return [t for t in taglist if t in mood_tags]

music['mood_tags'] = music['tags_list'].apply(filter_mood_tags)

In [ ]:
music[['tags_list','mood_tags']].head()

                                           tags_list mood_tags
0  [rock, alternative, indie, alternative_rock, i...        []
1  [rock, alternative, indie, pop, alternative_ro...    [love]
2  [rock, alternative, alternative_rock, 90s, gru...        []
3  [rock, alternative, indie, alternative_rock, i...        []
4  [rock, alternative, indie, alternative_rock, i...        []

In [ ]:
music['mood_text'] = music['mood_tags'].apply(lambda x: ' '.join(x))
music['mood_text'].head()

0
1    love
2
3
4
Name: mood_text, dtype: object

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()
tfidf_matrix = tfidf.fit_transform(music['mood_text'])

In [ ]:
tfidf_matrix.shape

(50683, 7)

In [ ]:
from sklearn.preprocessing import MinMaxScaler
import numpy as np

audio_features = music[['valence','energy','danceability','acousticness','tempo']].fillna(0)

scaler = MinMaxScaler()
audio_norm = scaler.fit_transform(audio_features)

In [ ]:
from scipy.sparse import hstack

final_features = hstack([tfidf_matrix, audio_norm])

In [ ]:
emotion_to_mood = {
    "happy": ["happy","uplifting","dance","upbeat"],
    "sad": ["sad","melancholic","emotional"],
    "angry": ["angry","aggressive","heavy"],
    "calm": ["calm","relax","soothing"],
    "love": ["love","romantic","soft"],
    "neutral": ["chill","mellow"],
    "disgust": ["dark","alternative"]
}

emotion_audio_profile = {
    "happy":   [0.8, 0.7, 0.8, 0.2, 0.7],
    "sad":     [0.2, 0.3, 0.2, 0.8, 0.3],
    "angry":   [0.3, 0.9, 0.6, 0.1, 0.8],
    "calm":    [0.6, 0.2, 0.3, 0.9, 0.2],
    "love":    [0.7, 0.4, 0.4, 0.6, 0.4],
    "neutral": [0.5, 0.5, 0.5, 0.5, 0.5],
    "disgust": [0.2, 0.6, 0.3, 0.1, 0.5]
}

In [ ]:
final_features.shape

(50683, 12)

In [ ]:
import numpy as np
import scipy

scipy.sparse.save_npz('music_features.npz', final_features)
music.to_csv('music_meta.csv', index=False)

In [ ]:
from google.colab import files
files.download('music_features.npz')
files.download('music_meta.csv')

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
from scipy.sparse import hstack
import numpy as np

def recommend_music(emotion, top_n=5):
    # 1. Mood text vector
    mood_words = emotion_to_mood.get(emotion, [])
    mood_query = " ".join(mood_words)
    mood_vec = tfidf.transform([mood_query])

    # 2. Emotion-based audio vector
    audio_vec = np.array(emotion_audio_profile[emotion]).reshape(1, -1)

    # 3. Combine text + audio
    emotion_feature = hstack([mood_vec, audio_vec])

    # 4. Similarity
    similarity = cosine_similarity(emotion_feature, final_features)

    # 5. Get top results
    top_indices = similarity[0].argsort()[-20:]
    np.random.shuffle(top_indices)
    top_indices = top_indices[:top_n]

    return music.iloc[top_indices][
        ['name', 'artist', 'spotify_id', 'spotify_preview_url']
    ]

In [ ]:
recommendations = recommend_music("happy", top_n=5)
recommendations

,name,artist,spotify_id,spotify_preview_url
30145,The Hook Up,Britney Spears,2aCEiCcjf3qiDKsPNahoF9,https://p.scdn.co/mp3-preview/76bf20743c44befb...
14585,Shut the Club Down,Girl Talk,6GJ9BTsYMQc6BZ8QxogDcw,https://p.scdn.co/mp3-preview/74afa67acde97b3c...
3363,Cobrastyle,Robyn,0STDTrqaIzTmcElohAmMEF,https://p.scdn.co/mp3-preview/90f6147decbe875e...
17156,Ooh Ooh Baby,Britney Spears,14GmOwrlL8PiO30DYBsMME,https://p.scdn.co/mp3-preview/92da52efcd2d4262...
4076,Same Old Thing,The Streets,2SpZXih2PRDXRN5NXjwClt,https://p.scdn.co/mp3-preview/db6c2fc440597eba...

In [ ]:
recommendations[['name', 'spotify_preview_url']].head(10)

                     name                                spotify_preview_url
30145         The Hook Up  https://p.scdn.co/mp3-preview/76bf20743c44befb...
14585  Shut the Club Down  https://p.scdn.co/mp3-preview/74afa67acde97b3c...
3363           Cobrastyle  https://p.scdn.co/mp3-preview/90f6147decbe875e...
17156        Ooh Ooh Baby  https://p.scdn.co/mp3-preview/92da52efcd2d4262...
4076       Same Old Thing  https://p.scdn.co/mp3-preview/db6c2fc440597eba...

In [ ]:
from IPython.display import HTML, display

def show_recommendation(row, detected_emotion):
    song_name = row['name']
    artist = row['artist']
    spotify_id = row['spotify_id']

    print(f"😊 Detected Mood : {detected_emotion}")
    print(f"🎵 Song         : {song_name}")
    print(f"🎤 Artist       : {artist}")

    spotify_url = f"https://open.spotify.com/track/{spotify_id}"
    display(HTML(f'<a href="{spotify_url}" target="_blank">▶️ Open in Spotify</a>'))

In [ ]:
detected_emotion = "happy"   # from image/text model

for i in range(len(recommendations)):
    print(f"\nRecommendation {i+1}")
    show_recommendation(recommendations.iloc[i], detected_emotion)

Recommendation 1
😊 Detected Mood : happy
🎵 Song         : You Make My Dreams
🎤 Artist       : Hall & Oates

Recommendation 2
😊 Detected Mood : happy
🎵 Song         : Good Thing
🎤 Artist       : Fine Young Cannibals

Recommendation 3
😊 Detected Mood : happy
🎵 Song         : Hell Yes
🎤 Artist       : Beck

Recommendation 4
😊 Detected Mood : happy
🎵 Song         : Same Old Thing
🎤 Artist       : The Streets

Recommendation 5
😊 Detected Mood : happy
🎵 Song         : Bloodline
🎤 Artist       : Ariana Grande